CREATE SCHEMA IF NOT EXISTS {0} AUTHORIZATION postgres;

DROP TABLE IF EXISTS {0}.{1};

CREATE TABLE IF NOT EXISTS {0}.{1} (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        locality varchar(128) NOT NULL, 
        state varchar(3) NOT NULL,
        postcode varchar(4) NOT NULL,
        created timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (id)
    );
